parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - 'jest-formatting'
extends:
  - alloy
  - alloy/typescript
  - eslint:recommended
  - plugin:jest/recommended
  - plugin:github/recommended
  - plugin:unicorn/recommended
  - plugin:jest-formatting/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
ignorePatterns:
  - coverage/
  - dist/
  - src/__tests__/**/*.js
  - tmp.js
rules:
  prettier/prettier: off
  max-params: ['error', 5]
  #complexity: ["error", 20]
  complexity: ['error', 25]
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
  github/no-then: off
  i18n-text/no-en: off
  filenames/match-regex: ['error', '^[_]?[a-z0-9-]+(.[a-z0-9-]+)?$']
  unicorn/switch-case-braces: ['error', 'avoid']
  unicorn/no-null: off
  unicorn/no-array-reduce: off
  unicorn/no-nested-ternary: off
  unicorn/prefer-string-replace-all: off
  unicorn/prevent-abbreviations:
    - error
    - allowList:
        fn: true
        Fn: true
        db: true
        tmp: true
        obj: true
        str: true
        opts: true
        Opts: true
        args: true
        Args: true
        param: true
        params: true
        Params: true
